export const sidebarNavigation = [
  { label: "Dashboard", href: "/dashboard" },
  { label: "Master Database", href: "/master-database" },
  { label: "Stakeholders", href: "/stakeholders" },
  { label: "Vendors / Clients", href: "/vendors-clients" },
  { label: "Projects", href: "/projects" },
  { label: "Calendar & Schedule", href: "/calendar" },
  { label: "Gantt & Timelines", href: "/gantt" },
  { label: "Payments Sent", href: "/payments-sent" },
  { label: "Payments Received", href: "/payments-received" },
  { label: "Expenses", href: "/expenses" },
  { label: "Procurement", href: "/procurement" },
  { label: "Shipments", href: "/shipments" },
  { label: "Receiving", href: "/receiving" },
  { label: "Deliveries", href: "/deliveries" },
  { label: "Rentals", href: "/rentals" },
  { label: "Compliance", href: "/compliance" },
  { label: "Finance", href: "/finance" },
  { label: "Taxation", href: "/taxation" },
  { label: "Advisors", href: "/advisors" },
  { label: "Pipeline", href: "/pipeline" },
  { label: "Careers & Staff", href: "/careers-staff" },
  { label: "File Center", href: "/file-center" },
  { label: "Reports", href: "/reports" },
  { label: "Settings", href: "/settings" },
  { label: "License", href: "/license" }
];
